---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-trigger
  namespace: exp
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  # secrets needed for Github/Gitlab interceptors
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger
  namespace: exp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-trigger
  namespace: exp
subjects:
- kind: ServiceAccount
  name: tekton-trigger
  namespace: exp
roleRef:
  kind: Role
  name: tekton-trigger
  apiGroup: rbac.authorization.k8s.io
