apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
  namespace: exp
spec:
  params:
  - name: message
    type: string
  steps:
  - name: echo
    image: "debian"
    command: ["echo"]
    args: ["$(params.message)"]