apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-mux-hello-world
  namespace: exp
spec:
  params:
    - name: directory
      type: string
    - name: dockerfile
      type: string
    - name: tag
      type: string
    - name: image
      type: string
    - name: deployment-name
      type: string
    - name: deployment-ns
      type: string  
  resources:
    - name: repo
      type: git
    - name: cluster
      type: cluster
  tasks:
    - name: test
      taskRef:
        name: test
      params:
        - name: directory
          value: "$(params.directory)"
      resources:
        inputs:
          - name: repo
            resource: repo
    - name: build-and-push
      runAfter: [test]
      taskRef:
        name: build-and-push
      params:
        - name: dockerfile
          value: "$(params.dockerfile)"
        - name: image
          value: "$(params.image)"
        - name: tag
          value: "$(params.tag)"
      resources:
        inputs:
          - name: repo
            resource: repo
    - name: deploy
      runAfter: [build-and-push]
      taskRef:
        name: app-deploy
      params:
        - name: deployment-name
          value: "$(params.deployment-name)"
        - name: deployment-ns
          value: "$(params.deployment-ns)"
        - name: deployment-image
          value: "$(params.image)"
        - name: deployment-tag
          value: "$(params.tag)"
      resources:
        inputs:
          - name: micro-k8s-cluster
            resource: cluster
