apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-mux-hello-world
spec:
  type: git
  params:
    - name: url
      value: https://github.com/anshulpatel25/go-mux-hello-world
    - name: revision
      value: main
