---
apiVersion: v1
kind: Secret
metadata:
  name: go-mux-hello-world-dockerhub-auth
  namespace: exp
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
    # Below needs to be updated with actual credentials
    username: <USERNAME>
    password: <PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: micro-k8s-cluster
  namespace: exp
data:
  # Below needs to be updated with actual credentials
  cadataKey: <CA_KEY>
  tokenKey: <TOKEN_KEY>
