---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: anshulpatel25-dockerhub-auth
  namespace: exp
spec:
  backendType: systemManager
  region: ap-south-1
  data:
    - key: /go-mux-hello-world/dockerhub/username
      name: username
    - key: /go-mux-hello-world/dockerhub/password
      name: password
  template:
    type: kubernetes.io/basic-auth
    metadata:
      annotations:
        tekton.dev/docker-0: https://index.docker.io/v1/

# https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#to-create-additional-api-tokens
# https://stackoverflow.com/questions/65393939/how-to-disable-creation-of-token-secret-creation-while-creating-a-service-accoun?noredirect=1#comment115623208_65393939
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-deploy-bot-token
  namespace: exp
  annotations:
    kubernetes.io/service-account.name: tekton-deploy-bot
type: kubernetes.io/service-account-token
