---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-docker-bot
  namespace: exp
secrets:
  - name: anshulpatel25-dockerhub-auth

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-deploy-bot
  namespace: exp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robot-cluster
subjects:
  - kind: ServiceAccount
    name: robot
    namespace: default
roleRef:
  kind: ClusterRole
  name: robot-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robot-cluster
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs: ["*"]
